[theme]
base="dark"

primaryColor="#22D3EE"

backgroundColor="#2F3A4A"              # gris bleu plus lumineux
secondaryBackgroundColor="#445066"     # cartes plus claires

textColor="#F8FAFC"                   # presque blanc mais doux

font="sans serif"
