[theme]
base="light"

primaryColor="#38BDF8"

backgroundColor="#DCE3EA"              # gris bleuté plus profond
secondaryBackgroundColor="#C7D2FE"     # léger contraste

textColor="#020617"                   # texte un peu plus marqué

font="sans serif"
